version: '3'
services:
  app:
    image: my-app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=
      - MYSQL_PASSWORD=
      - MYSQL_PORT=
      - MYSQL_USER=
