apiVersion: v1
data:
  rootpassword: cGFzc3dvcmQ=
  user: bXlzcWw=
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: "2023-06-11T01:40:27Z"
  name: mysql-password
  namespace: db-ns
  resourceVersion: "2393"
  uid: a395b922-4ebd-42e7-a171-54c6a7a8f19a
type: Opaque
