apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-06-11T01:30:49Z"
  labels:
    kubernetes.io/metadata.name: app-ns
  name: app-ns
  resourceVersion: "1913"
  uid: 739d250f-ff4e-487d-aa4b-f3e375bb6c86
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
