apiVersion: v1
kind: Service
metadata:
  labels:
    app: instabug-goapi
  name: instabug-goapi
  namespace: app-ns
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: instabug-goapi
status:
  loadBalancer: {}
