apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: yousefmeska/instabug-go:latest
          ports:
            - containerPort: 9090
          env:
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  key: rootpassword
                  name: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: dbname
                  name: app-cm
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: dbuser
                  name: app-cm
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: dbhost
                  name: app-cm
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: dbport
                  name: app-cm

---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - protocol: TCP
      nodePort: 30007
      port: 9090
      targetPort: 9090
